#!/usr/bin/env python3

from msyd.scripts.main import main
import sys
if __name__ == '__main__':
    if not (sys.version_info.major >= 3 and sys.version_info.minor >= 8):
        print("msyd requires at least python 3.8!")
    else:
        main(sys.argv[1:])
