name: Test example.sh

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

# Cancel if a newer run is started
# taken from https://github.com/nf-core/modules/blob/master/.github/workflows/nf-test.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Build msyd
      uses: ./.github/workflows/build.yml
      with:
        python-version: "3.12"
    - name: Test example_run.sh
      run: |
        # alias to a call launching the syri entrypoint from python
        # necessary, as the hacky git install does not install the CLI entrypoints
        alias syri='python <(echo "import syri.scripts.syri;syri.scripts.syri.main()")'
        ./example/example_workflow.sh
